/**
 * CONFIG - Auto-generated by build.js
 * Client: Tavares Chamber of Commerce
 * Do not edit manually - modify clients/tavares/client.json instead
 */

const CONFIG = {
    "mapbox": {
        "accessToken": "pk.eyJ1IjoicnlhbmRvbHBoanIiLCJhIjoiY21sOHI2OXRvMGE2ejNtcTMyajh0bWJtNCJ9.fDd6RAIarBzArdbZu8gfCA",
        "style": "mapbox://styles/mapbox/streets-v12",
        "center": [
            -81.732307,
            28.805161
        ],
        "zoom": 12,
        "minZoom": 3,
        "maxZoom": 18
    },
    "client": {
        "name": "Chamber of Commerce Interactive Map",
        "logoPath": "assets/logos/client-logo.png",
        "logoAlt": "Chamber of Commerce Logo"
    },
    "dolphLogo": {
        "logoPath": "assets/logos/dolph-logo.jpg",
        "logoAlt": "Dolph Map Company",
        "link": "https://dolphmap.com",
        "contact": {
            "name": "Marsha Duvall",
            "phone": "(954) 695-0327",
            "email": "mduvall@dolphmap.com"
        }
    },
    "banners": {
        "banner1": {
            "image": "assets/banners/premium/tavadora.jpg",
            "link": "https://www.tavadora.com/",
            "alt": "Tavadora Apartments"
        },
        "banner2": [
            {
                "image": "assets/banners/slideshow/peralta-dvoran-pa_banner.jpg",
                "link": "https://www.peraltaanddvoran.com/",
                "alt": "Peralta & Dvoran, PA"
            },
            {
                "image": "assets/banners/slideshow/infinity-financial-group.jpg",
                "link": "https://www.ifgfl.com/",
                "alt": "Infinity Financial Group"
            },
            {
                "image": "assets/banners/slideshow/BeltonBailBondsBanner.jpg",
                "link": "https://www.beltonbailbonds.com/",
                "alt": "Belton Bail Bonds"
            },
            {
                "image": "assets/banners/slideshow/atwater-apartments.jpg",
                "link": "https://www.atwatertavares.com/",
                "alt": "Atwater Apartments"
            },
            {
                "image": "assets/banners/slideshow/da-construction-inc.jpg",
                "link": "https://www.dabuilds.net/",
                "alt": "DA Construction, Inc"
            },
            {
                "image": "assets/banners/slideshow/uf-health.jpg",
                "link": "https://www.ufhealth.org/",
                "alt": "UF Health"
            },
            {
                "image": "assets/banners/slideshow/deas-consulting-llc.jpg",
                "link": "https://deas.consulting/",
                "alt": "Deas Consulting, LLC"
            },
            {
                "image": "assets/banners/slideshow/san-joses-mexican-restaurant.jpg",
                "link": "https://www.sanjosesoriginal.com/",
                "alt": "San Jose's Mexican Restaurant"
            },
            {
                "image": "assets/banners/slideshow/auto-ride-customs-ii.jpg",
                "link": "https://www.autoridecustoms.com/",
                "alt": "Auto Ride Customs II"
            },
            {
                "image": "assets/banners/slideshow/prestige-ford.jpg",
                "link": "https://www.prestigefordmtdora.com/",
                "alt": "Prestige Ford"
            },
            {
                "image": "assets/banners/slideshow/cousin-vinnies-family-restaurant.jpg",
                "link": "https://www.cvinnies.com/",
                "alt": "Cousin Vinnie's Family Restaurant"
            },
            {
                "image": "assets/banners/slideshow/tavares-village.jpg",
                "link": "https://www.tavaresvillage.com/",
                "alt": "The Cove at Tavares Village"
            },
            {
                "image": "assets/banners/slideshow/titan-roofing.jpg",
                "link": "https://www.titanroofingprofessionals.com/",
                "alt": "Titan Roofing"
            },
            {
                "image": "assets/banners/slideshow/advent-health.jpg",
                "link": "https://www.adventhealth.com/",
                "alt": "AdventHealth Centra Care"
            },
            {
                "image": "assets/banners/slideshow/symons-ac-heating-inc.jpg",
                "link": "https://www.symonsac.com/",
                "alt": "Symons AC & Heating Inc"
            },
            {
                "image": "assets/banners/slideshow/central-lakes-realty.jpg",
                "link": "https://www.centrallakesrealty.com/",
                "alt": "Central Lakes Realty"
            },
            {
                "image": "assets/banners/slideshow/bristol-park.jpg",
                "link": "https://www.bristolparkapartments.com/",
                "alt": "Bristol Park Apartments"
            },
            {
                "image": "assets/banners/slideshow/bristol-lakes.jpg",
                "link": "https://www.bristollakesapartments.com/",
                "alt": "Bristol Lake Apartments"
            },
            {
                "image": "assets/banners/slideshow/lake-tavares-townhomes.jpg",
                "link": "https://www.laketavarestownhomes.com/",
                "alt": "Lake Tavares Townhomes"
            },
            {
                "image": "assets/banners/slideshow/grace-assured-home-care.jpg",
                "link": "https://www.graceassured.com/",
                "alt": "Grace Assured Home Care Services"
            },
            {
                "image": "assets/banners/slideshow/belton-insurance.jpg",
                "link": "https://www.beltoninsuranceagency.com/",
                "alt": "Belton Insurance Agency"
            },
            {
                "image": "assets/banners/slideshow/Tavares-Pro-Shop.jpg",
                "link": "https://www.tavaresfl.gov/",
                "alt": "Tavares Prop Shop"
            }
        ],
        "slideshow": {
            "interval": 5000,
            "fadeTransition": 1000
        }
    },
    "data": {
        "csvPath": "data/advertisers.csv"
    },
    "markers": {
        "defaultColor": "#1a5276",
        "clusterEnabled": false,
        "customIcon": null
    },
    "cityLabel": {
        "name": "TAVARES",
        "position": [
            -81.7268,
            28.797
        ],
        "hideFromDefaultLabels": "Tavares",
        "hideAtZoom": 14
    },
    "chamberCallout": {
        "position": [
            -81.713,
            28.79
        ],
        "showAtZoom": 12
    }
};

// Verify that CONFIG is properly defined
if (typeof CONFIG === 'undefined') {
    console.error('ERROR: CONFIG object is not defined!');
}
